### ISSUE TITLE
KPI measurement for posts

### ISSUE THREAD

**Issue by c3c1l1a** [tunapanda/wp-data-kpis#2]
Get the number of posts and expose it through the filter mechanism

**Comment by limikael** [comment]
Here is some "pseudo code" illustrating how to implement the KPI measurement in a plugin. In this case it would be implemented internally in wp-data-kpis, but it would be done the same. I'm saying pseudo code because it is untested, so use as inspiration rather than source of copy+pasting... :)

	add_filter("register_kpis","registerMyKpis");
	add_filter("measure_kpis","measureMyKpis");

	public function registerMyKpis($kpis) {
		$kpis["my-test-kpi"]=array(
			"title"=>"This is my test kpi"
		);

		$kpis["my-other-test-kpi"]=array(
			"title"=>"This is my test other kpi"
		);

		return $kpis;
	}

	public function measureMyKpis($kpis) {
		$kpis["my-test-kpi"]=10;
		$kpis["my-other-test-kpi"]=5;

		return $kpis;
	}
